# This is a config for E2B sandbox template.
# You can use template ID (yxezvx1tznpjioqqzlfo) or template name (finished) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("finished") # Sync sandbox
# sandbox = await AsyncSandbox.create("finished") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('finished')

team_id = "a139f77f-babd-43ca-9890-44d3870bc356"
start_cmd = "/c.sh"
dockerfile = "e2b.Dockerfile"
template_name = "finished"
template_id = "yxezvx1tznpjioqqzlfo"
